### ISSUE TITLE
Self-Practice 2 Level 4 - Help with serveCruises logic

### ISSUE THREAD

**Issue by yqlok17** [nus-cs2030/2223-s1#115]
Require some help with regards to the logic of serveCruises.

Currently my code follows this process:

- Initialise loader with numOfLoaders from method call
- Using for-each loop, loop through each cruise
- for loop (from int i = 1 to i == cruise.getNumOfLoadersRequired) 
- Initialise int addServiceTime = 0
- Initialise a new Service with loader, cruise and addServiceTime as parameters and print Service
- Update loader to next loader, close loop
- Conditional to check if on last loader and cruise is not finished servicing: if (i % numOfLoaders == 0 and i < cruise.getNumberOfLoadersRequired()), add the cruise's service time to addServiceTime

Am able to pass the test case if the cruise has 2 or 3 loaders, but not 1 loader. I'm not sure on how to possibly increment the service time to accommodate the delay for any "waiting" cruises. Would appreciate any help here.

**Comment by OngMinXian** [comment]
Since the dock can only service one cruise at a time, maybe can consider how many cycles of loaders does it take to service the cruise.

Consider, NumOfLoadersRequired = 3 and numOfLoaders = 3, then you would need 1 cycle since 3 / 3 = 1.
Total service time would be 1 * serviceTime 

Consider NumOfLoadersRequired = 3 and numOfLoaders = 1, then you would need 3 cycles since 3 / 1 = 3.
Total service time would be 1 * serviceTime 

Consider NumOfLoadersRequired = 5 and numOfLoaders = 3, then you would need 2 cycles since 5 / 3 = 2 (rounded up)
Total service time would be 2 * serviceTime 

Hope this helps you calculate the time you need to add.

**Comment by euzhengxi** [comment]
Maybe you can consider initialising a variable that tracks the availability of the loaders. This variable refreshes for every arrival

**Comment by OliverChen0602** [comment]
I think your logic is correct and the mistake is just a minor one in counting the time taken :)
so maybe you can just write an or statement in your if condition to tackle the cases of having only one loader separately. My approach is to only add the extra time when it is the beginning of a new cycle, that is, when i % numOfLoaders == 1 && i > 1(so confirm there is a new cycle happening), this case is for numOfLoaders > 1, then for the case of 1, every increment of i is a new cycle, so just add || to tackle this case separately.

**Comment by emto17ab** [comment]
Have you figured this out? If not I am happy to help.

**Comment by yqlok17** [comment]
Have figured out the solution, thank you to everyone who commented!
