### ISSUE TITLE
Weird bug for Customers 4&6 in test case 4

### ISSUE THREAD

**Issue by wjiayis** [nus-cs2030/2223-s1#121]
Hi there,

So in my implementation, I push events into the pq at the ```serve``` stage. I face this weird issue where if I sync the servers before pushing them into the pq, I can pass test case 4 but not test cases 1, 2 and 3, and if I don't, I can pass test cases 1, 2 and 3 but not test case 4 (Customers 4 and 6 gets both served at time 2.500).

Has anyone encountered the same issue? Or how would you advice me to change my implementation?

Thanks in advance!

**Comment by timotius-jason** [comment]
Hi,

Perhaps you can give more details about your `serve` stage.

I did get a similar bug where I had a Server serving two Customers at the same time. For mine, I did not update the Server and the queue properly. Perhaps you can also check for these.

Hope this helps!

**Comment by junhuiii** [comment]
Had this problem as well so I'm going to make a guess and try and explain what is causing the issue.

If you look at test case 4, with your current implementation, at 1.700, Customer 6 arrives and waits, but at that queue, Customer 4 is already there and waiting. So when your `execute` method executes, it will create a ServeEvent for Customer 6 using the same "next available time" of the server as that in Customer 4. That's why directly after Customer 4 has been served, the next event in the PQ to be polled will be Customer 6's serve event. 

If you are experiencing the same issue with your implementation, you will need to implement a check that makes sure that when Customer 6's ServeEvent is polled, the server is actually free to serve Customer 6. If it isn't then, it means that you have to create a new ServeEvent with the next updated time, and put it back into the PQ.

Hopefully that wasn't too confusing.

**Comment by wilsonwid** [comment]
I think this issue can be resolved by having one source of truth for your `Server` class, rather than giving each `Event` a separate instance of a `Server` which may be 'out-of-sync', as this may cause the `Event`s pushed to the PQ after to have incorrect timings.

**Comment by bransometan** [comment]
Have a similar issue, but what I found out was there may be instances where your "server may be free but may have two customers at same time".  However, a server can only serve one customer at a time. Therefore, you need to implement your solution such that if there are customers with the same timings, then you can only serve one only. Also check that you update the correct server at the right time (I have a test case which I have been stuck for a long time but only realise later that I did not update the correct server).

**Comment by wjiayis** [comment]
Fixed this, thank you!
