### ISSUE TITLE
Technical Issue: Able to compile using javac but have errors when loading files into jshell

### ISSUE THREAD

**Issue by felibunnyy** [nus-cs2030/2223-s1#125]
<img width="935" alt="Screenshot 2022-09-27 at 4 50 20 PM" src="https://user-images.githubusercontent.com/105587981/192480174-fa44842f-eb01-4f5a-beb0-dc0f420f37f2.png">

Hi, I am able to compile using javac but when I load all the files into jshell, there are errors as shown in the screenshot. Alternatively, it works when I open jshell then manually open the files one by one into jshell but that is too troublesome.

Anyone have ideas as to why this happens?

**Comment by ZYN2122** [comment]
It could be because of the dependencies I believe for the upper portion. You may have used *.java but if I am not wrong, *.java will open it in alphabetical order and this may conflict with the dependency order. If you opened it manually as per below, perhaps you ordered the dependencies wrongly. 

For the bottom error, you should be opening the files outside of jshell when you do jshell (File).java. (You are in Jshell already).

**Comment by felibunnyy** [comment]
I see, thank you!
