### ISSUE TITLE
Help regarding Exercise 3

### ISSUE THREAD

**Issue by tranquilityyy** [nus-cs2030/2223-s1#131]
Not too sure if anyone has faced this issue, but I'm not exactly sure what the error means / how the error arose. All of my public test cases have passed and I've implemented the classes according to the instructions given on Level 6. 

Would be great if anyone could suggest where the error could be coming from. Thanks!

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/114040935/192782848-99631d9e-7030-47a6-b3ef-9767a3cc89a3.png">

**Comment by OliverChen0602** [comment]
Not too sure about the exact root of error but since now you are not able to "new" a SolidSphere/SolidCuboid object, I suggest that you go back to check the inheritance hierarchy of all your classes, since these two classes should be concrete implementations and therefore it should make sense to instantiate. Perhaps you disrupted the inheritance relation when you implement other classes after implementing these two. Hope it helps!

**Comment by liAiyujelly** [comment]
I'm not too sure about the symbol errors but for the one at line 40 I feel it might be something wrong with the getVolume() method defined in Shape3D interface? You can check if you have implemented this method in SolidImpl. But I think for this exercise you can pass the tests without using getters! hope this can provide some help:)

**Comment by tranquilityyy** [comment]
Thank you all for the suggestions!

As suggested by Oliver, the error was because I created a new object by calling the SolidImpl class within the mass method itself, which caused the method to be ineffective once the class was dropped (since the class can no longer be called to create a new object).

The solution was to instead declare a new object from the SolidImpl class once the SolidCuboid/SolidSphere was constructed (by shifting the creation of the object to the constructor method), so the properties would be retained even if the SolidImpl class is now dropped. (Or at least that was what eventually worked).
