### ISSUE TITLE
PA1 Practice Level5 Wrong output 

### ISSUE THREAD

**Issue by OngMinXian** [nus-cs2030/2223-s1#133]
I am unable to get the correct output and it seems for d and e, it prints all but the initial case. But it works when I printed it on my own in my Main. I am using recursion for getLineage to recursively call till it is not a ContactCase.

Problem:
![image](https://user-images.githubusercontent.com/95210624/192853235-24124351-83b3-40a0-ad5a-7ab64ad05dc1.png)

My output:
![image](https://user-images.githubusercontent.com/95210624/192853404-73249837-553c-4be7-8649-e4cd4972a75c.png)

**Comment by liAiyujelly** [comment]
I got the same error yesterday, and I think mine was caused by the test method in Case which returns a new Case instead of a new ContactCase, but for the public test here d is initiated as a Case and renewed by the test in Case. So I tried to override the test method in ContactCase and it worked. Hope this helps!

**Comment by OngMinXian** [comment]
> I got the same error yesterday, and I think mine was caused by the test method in Case which returns a new Case instead of a new ContactCase, but for the public test here d is initiated as a Case and renewed by the test in Case. So probably might not be the best method but I tried to override the test method in ContactCase and it worked. Hope this helps!

Thanks! This was indeed the problem!
