### ISSUE TITLE
PA1: rcv() cannot be invoked from r1

### ISSUE THREAD

**Issue by zandratay** [nus-cs2030/2223-s1#142]
Hi, for the following test case:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/88842830/193281638-2ea230fe-1925-41c5-bc3d-d8f0bca298cb.png">
How do we purposely cause the "Cannot find symbol" error for rcv() ? Is rcv() still declared in the Transmitter class or another child class that inherits from Transmitter/ Host?

**Comment by xuan-jun** [comment]
Hello, since `r1.rcv()` returns an error whereby you "Cannot find symbol", it means that the method `rcv()` should not exist within the `Transmitter` class since `r1` is a `Transmitter`. 

Therefore, it should be defined under the object that you return after **"a terminal (e.g. a pager) to initiate the handshake with a host (e.g. a transmitter)"** whereby we call the `snd` method (for e.g. `p1.snd(r1)`). Whether it inherits from Transmitter/Host depends on your implementation

Hope this helps!

**Comment by zandratay** [comment]
Hi, i tried what you mentioned above. at the moment i have a Transmitter class and a child class (called ConnectHost) which inherits from Host. ConnectBack is returned from the p1.snd(r1) method call. 
However, after refining the rcv() method in ConnectHost only, i face the following issues:
<img width="114" alt="image" src="https://user-images.githubusercontent.com/88842830/193483247-c00292d2-0c1d-43fd-9c82-7fb92505e74a.png">
how do you solve this? isn't the compile time type ConnectHost, hence it should be able to find the symbol `rcv()` ?

**Comment by quek-zhiheng** [comment]
hmm I'm not sure if ConnectBack vs ConnectHost is a typo, but if not then thats probably where the issue is at! Maybe there is another implementation but I think you should be implementing `rcv()` on whatever class that you are returning from the `snd()` method. In other words, if you are returning ConnectBack from the `snd()` method, then the `rcv()` method should be implemented on ConnectBack!

**Comment by zandratay** [comment]
@quek-zhiheng oh yes i meant `ConnectHost` (not ConnectBack). `ConnectHost `is the class that im returning from` p1.snd(r1)`.
However when i implement `rcv()` in `ConnectHost `**only** (not declared in Host and Transmitter), the "cannot find symbol" error appears. That is because the compile time type of `p1.snd(r1).rcv() `is `Host `right? How were u able to resolve this issue?

**Comment by quek-zhiheng** [comment]
oh this is quite strange then but the compile time type should be ConnectHost if the return type of your `snd()` function is ConnectHost! But I guess you might want to check if the method signature of `rcv()` is different too, in case you may have accidentally declared it with an input or something :")
