### ISSUE TITLE
PA1: Level 5 Compilation Error

### ISSUE THREAD

**Issue by bransometan** [nus-cs2030/2223-s1#145]
![image](https://user-images.githubusercontent.com/64539315/193336084-b706548f-ed5e-4f9a-ab4d-92327a80690b.png)

Hi, for last part of this level, may I know how can we generate a compile error for this. Since snd method will always take in a host and p1.snd(r1) will always return a host, then p2.snd(p1.snd(r1)).rcv().ack() will always execute without compile error? Or is there a better approach to this?

**Comment by timotius-jason** [comment]
Hi,

Perhaps you can refer to this issue https://github.com/nus-cs2030/2223-s1/issues/142 for some clue. Hope it helps!

**Comment by bransometan** [comment]
Hi, now for my `p1.snd(r1)`, it returns a new object but inherit from the Host. Then, my snd method takes in a Host `snd(Host host)`. Therefore when I pass in `p2.snd(p1.snd(r1))`, it will still execute without error since `p1.snd(r1)` Is-a "Host". Should my `p1.snd(r1)` inherit from something else which is not a Host? Or is my above approach wrong here.

**Comment by xuan-jun** [comment]
Hi, the way I interpreted this incompatible type is that for those objects that come out of a `snd()` method, we should not be able to pass it into a `snd` method since they have yet to complete the handshake.

You can try to think of how you want to design your objects such that you can still pass in a `Host` that has yet to make any connections / a `Host` that has established at least one connection into the `snd()` method **but** for a `Host` that has an incomplete handshake, it shouldn't be allowed to be passed in.

Do note that the object that comes out of `snd()` method should still be a `Host` because under level 2, it is still equals to a `Host` so you should not break that part.

```
jshell> Host h1 = r1
h1 ==> transmit1

jshell> new Host()
|  Error:
|  Host is abstract; cannot be instantiated
|  new Host()
|  ^--------^

jshell> p1.snd(r1).equals(h1)
$.. ==> true

jshell> r1.equals(h1)
$.. ==> true

jshell> h1.equals(p1)
$.. ==> false
```

Hope this helps!

**Comment by bransometan** [comment]
Tha

> Hi, the way I interpreted this incompatible type is that for those objects that come out of a `snd()` method, we should not be able to pass it into a `snd` method since they have yet to complete the handshake.
> 
> You can try to think of how you want to design your objects such that you can still pass in a `Host` that has yet to make any connections / a `Host` that has established at least one connection into the `snd()` method **but** for a `Host` that has an incomplete handshake, it shouldn't be allowed to be passed in.
> 
> Do note that the object that comes out of `snd()` method should still be a `Host` because under level 2, it is still equals to a `Host` so you should not break that part.
> 
> ```
> jshell> Host h1 = r1
> h1 ==> transmit1
> 
> jshell> new Host()
> |  Error:
> |  Host is abstract; cannot be instantiated
> |  new Host()
> |  ^--------^
> 
> jshell> p1.snd(r1).equals(h1)
> $.. ==> true
> 
> jshell> r1.equals(h1)
> $.. ==> true
> 
> jshell> h1.equals(p1)
> $.. ==> false
> ```
> 
> Hope this helps!

Thanks for your help! I managed to solve it with your advice!
