### ISSUE TITLE
JShell cannot recognize symbol

### ISSUE THREAD

**Issue by SungMatt** [nus-cs2030/2223-s1#149]
JShell has been plagued with issues regarding opening classes that are compilable with javac, but for some reason can't be instantiated in Jshell.

Here's an example.
<img width="422" alt="Screenshot of jshell terminal" src="https://user-images.githubusercontent.com/6725727/193438466-cf8910b9-114c-4c53-9019-e46503d4f3a4.png">
Does anyone else have this issue? I've been blindly uploading to CodeCrunch instead, to watch it fail, rather than be able to test it myself, since I can't even make a simple class.

**Comment by xuan-jun** [comment]
Hi, it seems that the problem here is that under your `Pager` class, `toString()` method, you are making use of `this.getName()` but the method has not been instantiated yet.
Since the `getName()` method is not instantiated, it gives you the error that you cannot instantiate a new `Pager` object.

Hope this helps!

**Comment by mohddanesh** [comment]
i agree with the above. this is no getName() method in the class Pager yet

**Comment by SungMatt** [comment]
Ah. Am idiot. Re-opened the file I edited and all's good now. Thank you all!
