### ISSUE TITLE
Stuck at Test Case #8 not sure how to proceed

### ISSUE THREAD

**Issue by EkMi00** [nus-cs2030/2223-s1#152]
# Summary
Stuck at Test Case #8 for a while

## Description 
I believe might be the queuing up of customers seeing as how customer 9 has queued up for the first server queue instead of the second one. 

I believe I have followed the instructions:  
"if all servers are serving customers, then the customer that just arrived scans the queues from 1 to N, joins the first queue that is not full (not necessarily the shortest) and waits in the queue (WAIT event). Note that a customer that chooses to queue joins at the end of the queue. " 

So I have trouble seeing the issue, any help is appreciated.

## Screenshots (if any): 
![Screenshot (488)](https://user-images.githubusercontent.com/110707998/193633137-a150f0c3-e937-43f6-8dc2-ba5e9aa6cfba.png)

**Comment by Ryan-loves-movies** [comment]
Just from the errors, my best guess is that it seems to be a problem with the checking of the server queue given there are consecutively "44.000 4 serves by 1" and "44.000 7 serves by 1". Customer 7 should join the queue (WAIT event) but not be served.

The error of "9 serves by 1" also seems to be caused by the same error since for some reason the program is not registering that server 1 is not free between 44.000 and 57.000 while it's serving customer 4.

**Comment by renachongpq** [comment]
I got the same error as what you got at line 25 & 26
It depends on your implementation, if you were updating 
`Server` along the way, you might want to check if your `Server` was updated correctly. Currently what is happening is that the serve time of customer 7 is taking in the time the service ends for customer 3. 

Not sure if the problem you are facing might be slightly different from mine, as your served time for customer 5 seems to affected even though customer 5 arrived earlier than other customers behind

**Comment by EkMi00** [comment]
Thanks for all the comments, the discrepancy was because I did not update the queue properly during the transition from Wait to Serve.
