### ISSUE TITLE
wrong service time in code crunch

### ISSUE THREAD

**Issue by joeyHXD** [nus-cs2030/2223-s1#175]
In the hidden test cases of code crunch, after looking at the test output, it seems that

    customer 4 has service time of customer 6
    customer 6 has service time of customer 4

    customer 5 has service time of customer 8
    customer 8 has service time of customer 5

    customer 7 has service time of customer 9
    customer 9 has service time of customer 7

and the error just continues...
 However I cant seem to reproduce this error after trying a few different test.in. 
The test.in in the pdf works fine.
My project 1 also works fine in code crunch (i only changed around 2-3 lines of code for lab 5).
Anyone has a clue what might be causing this?

my simulator runs roughly like this:

    for i in inputTimes:

        make a dummy customer with only arrivalTime
        make a Arrive event, add it to PQ
        Then pop all the event in PQ before the Arrive event
        Pop the Arrive event from PQ
        (if there is available server/queue then) replace customer with arrivalTime and ServiceTimeSupplier.get()
        get the next event of Arrive and add it to PQ

    clear whatever is left in PQ

**Comment by jingyiiiiz** [comment]
Hi I encountered the same issue when doing this question. I think what the test cases expect is that the service time for customers are only retrieved when the customer is being served. Thus since customer 6 is served before customer 4, the service time of customer 6 should be retrieved first. What I did last time was retrieving the service time when waiting events are evaluated. This tends to produce errors in this case since customer 6's service time should be before customer 4's. Hope this helps!

**Comment by xBoommy** [comment]
Hi, if we can only retrieve the service time of customers during their service event, how would it be possible to generate the service events of customers that need to wait?

Say a customer X arrives and joins a queue, it would go from an arrival event to a wait event which is processed immediately. The wait event would then have to generate a service event but the time of this service event for customer X would depend on existing customers in the queue where the service event would start after all the customers in the queue are served. However, there would be cases where the customers in the queue have not been served and we cannot retrieve their service time yet. How would we then determine the start time of the service event for customer X without knowing how long the queue time is (because we don't know the service duration of customers in the queue)?

**Comment by joeyHXD** [comment]
> Hi I encountered the same issue when doing this question. I think what the test cases expect is that the service time for customers are only retrieved when the customer is being served. Thus since customer 6 is served before customer 4, the service time of customer 6 should be retrieved first. What I did last time was retrieving the service time when waiting events are evaluated. This tends to produce errors in this case since customer 6's service time should be before customer 4's. Hope this helps!

oh I see! thank you so much!

**Comment by jingyiiiiz** [comment]
Hi @xBoommy , it is true that we can only know that service time when the service event is processed. Therefore I changed my previous structure for project 1 (which evaluates wait event to generate its serve events) to something like returning serve event from done events. In this way we can determine next serve event's time from the current timings.

**Comment by xBoommy** [comment]
@jingyiiiiz Thanks for the reply! I'll give it some thought.

**Comment by zhanyi3** [comment]
hi, @jingyiiiiz I am facing the same problem. for my project 1 I too updated the server next available time when Arrive/Wait is evaluated to Serve. you mention returning Serve Event from Done Event. I am not sure how to go about this. Since there is already a PQ of all Arrival Events of all customers generated, if I return Serve Event from Done Event of another customer would that not result in duplicated events of one customer?

**Comment by jingyiiiiz** [comment]
Hi @zhanyi3, so what I did was not returning the Serve Event of the same customer, but the serve event of the **next customer** in the waiting queue of that counter (ofc no serve event should be returned if no one is in the queue when the previous customer is done serving).

**Comment by liAiyujelly** [comment]
hi @jingyiiiiz, can I ask if Serve Event is returned from Done Event how to avoid cyclic dependency cos Serve is also returning Done Event returning? thank you!

**Comment by zhanyi3** [comment]
hi @jingyiiiiz sry maybe I wasn't clear. I get that you meant the next customer but I am still confused because of the nature of `PQ`. for eg the case below
```
test case:
1 2 3
0.5
0.6
0.7
1.0
1.0
1.0

first event is polled from PQ:
---
0.5 1 arrives
0.6 2 arrives
0.7 3 arrives 
---
0.5 1 serves by 1
0.6 2 arrives
0.7 3 arrives
---
0.6 2 arrives
0.7 3 arrives
1.5 1 done serving by 1
---
0.6 2 waits at 1
0.7 3 arrives
1.5 1 done serving by 1
---
```

before I return `Serve` of 2 from `Done` of 1, I can't reach the `Done` or rather I can't proceed without processing the wait due to the nature of PQ. Am I missing something?

**Comment by jingyiiiiz** [comment]
Hi @liAiyujelly, yes I faced the same issue of getting cyclic dependencies because of the next event. So what I did was adding a kind of checker into simulator's simulate to check whether the event is a done event && there's a person waiting in queue, if so -> serve event is created and put into the queue. It works but I'm not so sure if this is a good design... If you have any other thoughts about the design maybe can share!

**Comment by jingyiiiiz** [comment]
Hi @zhanyi3, ohh I see what you mean. What I did was that when processing the waiting event, I did not do anything (since we cannot extract service time during waiting event). Hope this helps!

**Comment by zhanyi3** [comment]
ah I see... thanks! this cleared my doubts

**Comment by BlabbyDuck** [comment]
@jingyiiiiz Hello! 

> Hi @zhanyi3, ohh I see what you mean. What I did was that when processing the waiting event, I did not do anything (since we cannot extract service time during waiting event). Hope this helps!

@jingyiiiiz hello! When you say you didn't do anything, does it mean that u don't call the nextEvent function of wait?

**Comment by jingyiiiiz** [comment]
@BlabbyDuck Hi, yes that's what I did.

**Comment by BlabbyDuck** [comment]
@jingyiiiiz thank you! I managed to solve the issue :D
