### ISSUE TITLE
Exercise 5 Level 6: Incompatible type error

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2030/2223-s1#182]
Hi, I don't understand why ? extends Maybe<? extends R> cannot be substituted with Maybe<R>

![image](https://user-images.githubusercontent.com/82555990/195045834-8edad369-d477-42a4-bf2f-fad07aaf7778.png)

![image](https://user-images.githubusercontent.com/82555990/195045988-ab479668-18a5-47df-8d01-8facf85e86a6.png)

**Comment by wilsonwid** [comment]
I think this is because `Maybe<? extends R>` means that it is either `Maybe<R>` or in any `Maybe` with a type parameterisation that extends from `R`. In the second case, it cannot be directly converted to `Maybe<R>` and hence the error occurs. Perhaps the link below will be useful for you to understand this!
[https://docs.oracle.com/javase/tutorial/java/generics/subtyping.html](https://docs.oracle.com/javase/tutorial/java/generics/subtyping.html)

**Comment by bransometan** [comment]
I have exactly the same issue with you initially. If you look at the error given, you are trying to return a `Maybe<? extends R>` into a `Maybe<R>`. As of current, your `mapper.apply(this,thing)` returns a `Maybe<? extends R>`. Instead, what you should do is to find a way to make your `mapper.apply(this,thing)` returns a `Maybe<R>`. I hope this helps you to understand the error better.

**Comment by ziyi105** [comment]
Ah i get why there is an error now! Could you please give me some hints on how to convert Maybe<? extends R> to Maybe<R>? I have been thinking for hours already yet I still dont know how to do :")

**Comment by wilsonwid** [comment]
#178 might help! TL;DR: use a function that you've implemented previously.

**Comment by BlabbyDuck** [comment]
@ziyi105 Hello! May I know your approach to this issue? I have the same exact problem as you

**Comment by ziyi105** [comment]
I used the orElse method to solve it!
