### ISSUE TITLE
Lab5 test8 wrong service time

### ISSUE THREAD

**Issue by qitiancong** [nus-cs2030/2223-s1#183]
# Summary
Customer 6 got wrong input time which affects all subsequent customers; however .get() is only called in the constructor of Serve event.

if .get() was called in the wrong order, why will there be enough inputs? wont there be not enough service time for scanner?

<img width="636" alt="Screenshot 2022-10-11 at 15 08 02" src="https://user-images.githubusercontent.com/65145100/195069154-86db8568-438d-4559-8b3a-c061b9ea7355.png">
## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by lanqinggg** [comment]
Helloo! The sequence of .get() should be called in the service order, so for example if 4 reaches earlier than 5 but 5 is served before 4, .get() of 5 should be called before that of 4. I think you can try to check whether your code can do this

**Comment by liewyungjun** [comment]
#175 might be helpful

**Comment by bryanolm99** [comment]
Hi! You might want to avoid calling .get() in the constructor of Serve if your implementation is such that the time of creation of a Serve does not necessarily equate to it's time of execution. You can either ensure that .get() is only called within the execution of a Serve or modify your logic to ensure that the time of creation of a Serve is equal to its time of execution.

> if .get() was called in the wrong order, why will there be enough inputs? wont there be not enough service time for scanner?
Since your current implementation only calls .get() when constructing a Serve, the number of .get() should still be equal to the number of inputs. That's probably why you don't get an error.

**Comment by qitiancong** [comment]
thank you everyone for helping

**Comment by qitiancong** [comment]
> @qitiancong Did you restructure your code such that there is one PQ, or multiple PQs?

1 PQ which handles all events
