### ISSUE TITLE
Question about Maybe

### ISSUE THREAD

**Issue by GarlicButterSteak** [nus-cs2030/2223-s1#188]
Hi! I have some questions about Slide 4 of Lecture 7. (1) Why is there a \<T> in the method: static \<T> Maybe\<T> of (T thing), and (2) why is the method called “of” and (3) declared static? I tried to find online resources but I don’t really know what to search. (4) Also, I don’t really understand what a context is - is there an intuitive way of looking at it? Tanks in advance!

**Comment by junhuiii** [comment]
Hi, Prof Henry has already went through your questions pretty comprehensively in the lecture, so you may want to watch the lecture web-cast on Luminus for the full explanation.

In any case: 
1) .of() is a factory method, which means that it is a way for the client to create the object without calling `new ImList<Integer>` for example. However, when generics are involved, the factory method cannot reference the `<T>` defined in the class, because the object hasn't even been created yet. So the <T> in the `static <T> Maybe<T> of (T thing)` is referring to a DIFFERENT generic. You can code out the lecture code and change the `T`s there to U or any other alphabet and java will still compile it.

2) The method is called .of() simply by convention, which indicates that you want to create an object of (something). For example, consider List.of(1,2,3) means that we want to create a List containing 1,2,3.

3) Reason the .of() method is declared as static is precisely because it is a factory method, something like a constructor. The object hasn't been created yet, so in order to be able to access that method, it has to belong to the class Maybe directly, instead of an instance of Maybe, which is why we use `static`. 

4) Can't really describe this words, but maybe you can try rewatching the lectures and try the practice exercises on codecrunch to get a feel of what a context is. 

Hope this helps!
