### ISSUE TITLE
Other Possible Business Logics?

### ISSUE THREAD

**Issue by GarlicButterSteak** [nus-cs2030/2223-s1#191]
Hello everyone! I’m kinda interested to see if anyone had any thoughts on an alternate logic for the project as I think my current solution does not seem very smooth…

So originally with the service times supplied for all customers at the start, the Arrive -> Wait -> Serve chain was much smoother imo; that is, from the simulator (my manager) I could just directly call all the necessary ProcessEvent methods, i.e. Arrive returns a Wait Event and Wait Event returns a Serve Event and so on…

However, in order to account for the delayed process of getting the service times and anticipate the possibility that my queue for any server can be very long, I severed the Wait -/-> Serve chain. Instead, from the simulator, I additionally check if the polled event is a Done Event with the respective Server with a non-empty queue (unsmooth thing 1) and directly construct a Serve Event in the simulator itself (unsmooth thing 2) to be passed back into PQ, and so this just does not seem really optimal though it’s functional, but I can’t seem to think of an alternate logic that is smoother or more “elegant”. Any thoughts are appreciated! Thank you!

**Comment by timotius-jason** [comment]
Hi,

Perhaps you can refer to #176 for some inspiration.

**Comment by GarlicButterSteak** [comment]
> Hi,
> 
> Perhaps you can refer to #176 for some inspiration.

Hey thanks for linking the post, I must have missed it! I will read the comments more deeply again later but on a first reading my worry is that it seems the focus on the max queue size being 2 (?) (kindly correct me if I am reading the post wrongly) may not account for say, a server with a max queue size of >2 like 100. I’ll leave my post open for awhile more!

**Comment by zhanyi3** [comment]
I think what you are saying about one queue being too long is a valid consideration in reality but I remember in the project#1 document it did state the criteria of scanning from 1 to N and "not necessarily the shortest" so I dont think we have to worry about optimisation for this project. 
As for implementation, I did the same as you for project#1 submission and I agree that it is way more elegant than what I have after lab#5. I tried both your current method (Done -> Serve) and repeated Wait event and I personally find that repeated Wait seems smoother since in simulator I still only deal with events without dealing with servers and customer whereas when I did (Done -> Serve) I had to deal with them in the simulator. I can't keep the abstraction otherwise it results in cyclic dependency. I'm sure there must be a better way but repeated Wait is my best one so far.
