### ISSUE TITLE
Function<? super T,  ? extends R>

### ISSUE THREAD

**Issue by Prabhav10** [nus-cs2030/2223-s1#223]
In Lecture 7, the **map** method in **Maybe<T>** takes in a parameter **mapper** of type **Function<? super T,  ? extends R>**. 

I understand why the output of **mapper** can be any subclass of **R**. However, I am struggling to think of a concrete example to show when **mapper** takes in a type of **? super T**. Can anyone please provide an example?

**Comment by xuan-jun** [comment]
Hello, from the way I understand it
 
Suppose that we have a **Maybe<Integer>**, if we were to have a Function, mapper, we will want to be able to take in **Integer** as an input no matter what and then transform it to R.

We can think of **Integer** as a big circle and within it, you have all its parent classes (i.e. **Number**, **Object**) since Integer inherits from its parent class and will contain all the attribute/methods from it.

If we were to have a Function that takes in a **Number**, it will be able to accept **Integer** as an input since **Integer** is substitutable for **Number** (**Integer** is a child of **Number**). We will essentially be looking at the small part of **Integer** that contains **Number**. Similarly for a Function that takes in an **Object**, it will also be able to accept **Integer** as input since **Integer** is substitutable for **Object** (**Integer** is a child of **Object**)

Therefore, we can have the Function be **? super T** as the input. Since for any function that only looks at T or its super class, we can ensure that all the attributes and methods required for the Function are present to perform operations to map to R.

Hope this helps!

**Comment by wilsonwid** [comment]
Perhaps another idea would be that you might want to map an `ImList` using the attributes common to the elements of that `ImList`, hence you want to have a `Function` that is able to process the inputs using the attributes of `T` or `? super T`.

**Comment by Ryan-loves-movies** [comment]
Any function that takes in something more general than T (for e.g. Object) will only need to access methods that T has to have inherited (for e.g. inherited equals() from Object). This means that as long as the Function is one that takes in something more general than T, the function will only use methods that T definitely has inherited.

**Comment by acekhoon** [comment]
The idea is this: your function can take in more general type than your designated input type and can output more specific types that are subclass of the desired output. For instance, suppose that there is a function that takes in an integer and outputs circle. Then, the input of your function (which is 3 for example) is also an object, so the input can be Object 3. That's why the input can be anything super, while the output can be more general (filledcircle for instance) which is also a circle, so it can be more generalized to ? extends R.
