### ISSUE TITLE
Exercise 1 Stream

### ISSUE THREAD

**Issue by bransometan** [nus-cs2030/2223-s1#226]
![image](https://user-images.githubusercontent.com/64539315/197823148-68ca32a8-d1fd-415f-a61e-9caf4f5b3d98.png)
Hi, I'm trying to reattempt exercise 1 using streams but I am stuck with the test cases above.

What I did was use an `IntStream.range(0, points.size() - 1)` to compare with `points.get(x)` and `points.get(x + 1)` to check for the conditions. Then I did another mapping to `points.stream()` to check for `createUnitCircle(points.get(x), points.get(x + 1)).contains(y)` and count them. Then I did a reduce to find the max out of all the results. I am not sure which part of the logic is wrong and is there a better approach to this? Thank you.

**Comment by junhuiii** [comment]
Hi I think you are missing out on the number of UnitCircles you are supposed to create. Doing it without Streams, for a List of say 4 points, represented by [P1, P2, P3, P4], you are supposed to generate 6 combinations of UnitCircle: [P1P2, P1P3, P1P4, P2P3, P2P4, P3P4].

Your stream however is only generating 3 combinations of UnitCircle, since you are only iterating through the adjacent points [P1P2, P2P3, P3P4].

Hope this helps!

**Comment by bransometan** [comment]
Thanks for you help! I changed my implementation and it works now.

> Hi I think you are missing out on the number of UnitCircles you are supposed to create. Doing it without Streams, for a List of say 4 points, represented by [P1, P2, P3, P4], you are supposed to generate 6 combinations of UnitCircle: [P1P2, P1P3, P1P4, P2P3, P2P4, P3P4].
> 
> Your stream however is only generating 3 combinations of UnitCircle, since you are only iterating through the adjacent points [P1P2, P2P3, P3P4].
> 
> Hope this helps!
