### ISSUE TITLE
Exercise 6 Task 4

### ISSUE THREAD

**Issue by cherylchan02** [nus-cs2030/2223-s1#228]
Hi I'm not really sure how to approach creating generateRule() for task 4. I would appreciate any hints :"" also just to check, the method is supposed to generate a function that takes in a list and returns a new list with the next generation right?

**Comment by Tristanlimyr** [comment]
Hi, since generateRule() returns a UnaryOperator, u can write something like 
    return list  -> .... (operations to perform on list). 
So you are returning a lambda expression used to define and initialise a UnaryOperator.
Yes, the UnaryOperator should take in List<Integer> and return List<Integer>.

**Comment by OngMinXian** [comment]
Hello

To add on, what I did was split the input eg. 0, 0, 1, 0, 0 into 3 parts
the first element, the last element and the rest (middle section) because the first and last element only has one neighboring element to check.
I used .box() and .get(i) to check whether I need to convert the integers and then create 3 new Stream<Integer> and then joined them together using concat.

**Comment by ryanquek22** [comment]
Hello

You are right that the UnararyOperator is a function that takes in a List<Integer> and returns a List<Integer>.
[0,0,1,0,0] -> [0,1,0,1,0]
generateRule() is similar to writing a function that takes in a List<integer> and returns the new List<Integer> everytime the rule defined in Unarary Operator is called.

**Comment by cherylchan02** [comment]
hi everyone thanks for the help i managed to solve it already.
