### ISSUE TITLE
Unable to replicate test case as shown in CodeCrunch for Lab 6

### ISSUE THREAD

**Issue by glendon29** [nus-cs2030/2223-s1#229]
Hi Im unable to get the rest time for Server 1 before serving Customer 10. I tried to log and found out that the random value that it is returning is 0.0. Would greatly appreciate any help or hints if u encountered this issue

<img width="442" alt="image" src="https://user-images.githubusercontent.com/29744561/198215806-7237d510-1e2c-48b0-a11d-728c456fda9b.png">

**Comment by SungMatt** [comment]
Did you create another event for the Server to rest? All servers need to rest; but the duration of their rest may be 0.

**Comment by glendon29** [comment]
For my current implementation, Im calling .get() when each customer is being served and add it to the server next available.
Additionally what do u mean by create another event for Server to rest

**Comment by Tristanlimyr** [comment]
Hi, I have encountered the same problem as you. For me, it was because I called restTimes.get() when serve event occurs which messes up the order. This is because restTimes.get() should only be called after serve Event is done. Given two serve events A and B, A can start serving earlier than B but finish serving later than B. In this case, restTimes.get() should be called at B first then A instead of the other way round. Since the order of restTimes() is wrong, this caused my server 1 and 2 to rest for wrong duration.

**Comment by dohaduong** [comment]
I think you have the same problem as #224 , you could try calling .get() after each Done event instead of Serve

**Comment by dohaduong** [comment]
I think you have the same problem as #224 , you could try calling .get() after each Done event instead of Serve :)

**Comment by glendon29** [comment]
Ayo thanks alot guys got it working now. Thanks for the help and guidance
