### ISSUE TITLE
[Lab 7 Mock PA2] Level 1 Num Private Constructors

### ISSUE THREAD

**Issue by qwertyKey-s** [nus-cs2030/2223-s1#238]
# Summary

How to write Num constructors required for `.of(int i)` and `.zero()` methods? Please send helpp

## Description:

I get that for `.zero()` method, Num requires `private Num(AbstractNum<Integer> i) {...}` constructor, but I'm not sure how to implement it, i.e what should go into `{...}` . For `.of(int i)` method, I don't even know how to get started...Please gimme some hints....seems like I might flunk PA2 :(

**Comment by zhanyi3** [comment]
for `private Num(AbstractNum<Integer> i) {...}` constructor you can just call the constructor of `AbstractNum` using `super(...)` as for what goes into `(...)` you can think of how to make use of the `opt` attribute of the given input `i` together with `Predicate valid`.

**Comment by bransometan** [comment]
I think for all the private constructors in `Num`, you can just follow exactly what `AbstractNum` have and use `super` to call the parent constructors. Since `.zero()` method is provided, you also need to declare another private constructor in `Num` that takes in `AbstractNum`. In `of(int i)` method, you can make use of the predicate given `AbstractNum.valid` to test for `int i`. If valid, you can just return the result as usual. Else, you can return an `Optional.empty()` so `toString` in `AbstractNum` will print the other value.

**Comment by stanvewidjaja** [comment]
For `.zero()`, you just copy-paste the problem's specification. 

The real question is, how do you construct a Num from an AbstractNum<Integer>? Isn't it contradictory to pass a superclass to its' subtype's constructor?

Hint: look at superclass' constructor and see what is the best way to construct it **using itself**.

For `.of(int i)`, you would need to check if it's valid first, then pass the checked **redacted** to Num's constructor. Also, some of `.zero()`'s logic could be re-used here (especially the Num's constructor that has a signature of **redacted**).

_My answer in #234 could help_

**Comment by acekhoon** [comment]
Num is inherited from AbstractNum, but specifically, AbstractNum<Integer> since you have to specify generic type. For of method, it is static method and its implementation is very similar to maybe we covered in lecture 7 (which also includes private constructor with static of method). For zero, since the input is explicitly abstrctnum, you have to overload private constructor for num which accepts abstractnum with 0 value.

**Comment by glendon29** [comment]
Hi after reading these tips , Im still quite lost on how to implement the private constructors for the Num. Would be grateful if anyone can explain further  , or maybe show any examples on how to implement

**Comment by harriswarburton** [comment]
I'm also struggling to get started on lvl 1, getting compilation errors such as 'no suitable constructor found for AbstractNum(Optional<Integer>) and 'Num.java uses unchecked or unsafe operations'.

**Comment by giorgiocana** [comment]
I had the same issue. You just need to have a private constructor that takes in an AbstractNum, then use the super method that takes in its optional. From there, it should be all good.

**Comment by dohaduong** [comment]
For the private constructor `Num(AbstractNum<Integer> i)`, what i did was simply put `super(i.opt)` so that the parent takes in i.opt as its opt
