### ISSUE TITLE
Lab 7 Level 3

### ISSUE THREAD

**Issue by liAiyujelly** [nus-cs2030/2223-s1#257]
## Description:

Hi for level 3 the sub method I have countered the runtime issue. Every time when sub is evoked it takes very long to give the correct output. I used map and the function n in AbstractNum to negate the value just like how the question described and added back 'this', and then I used filter and valid in AbstractNum to check for the final result's validity. Any help or hint on how to do it in a faster way is appreciated!

## Screenshots

Screenshots (if any)

**Comment by OngMinXian** [comment]
Maybe its not taking very long but you have an infinite while loop.
Did you perhaps negated the wrong number and added the number (opposite)?
While I did was to make 
Num negatedNum = .....
then use a 'special add' to add this negatedNum since my normal add checks if Num >= 0.
This 'special add' blindly adds the negative negative num and then check if the resulting Num >= 0 before returning it.

Maybe you can explain your implementation of add since sub involveds add

**Comment by liAiyujelly** [comment]
Thank you for the advice! I went back and checked my add method and realised that I never really check for if the numbers are positive, and then it was indeed caused by an infinite loop because I used the equals method to check if it's time to stop the while loop but it won't work normally for negative numbers, so I followed your suggestion and it works now:)
