### ISSUE TITLE
PA2 Level 1 compareTo

### ISSUE THREAD

**Issue by giorgiocana** [nus-cs2030/2223-s1#277]
# Summary
Hi, I have been trying to implement the compareTo(T o) method, but I can't see how we can compare an Operator<T> to a T object. My Operator<T> has two properties: the BinaryOperator<T> and an int denoting the precedence.

However, object T does not have these properties, so how are we supposed to check its precedence?

Thanks in advance :)

**Comment by Justinn-Paul** [comment]
i compared it to another Operator and returned the difference in precedence values, not sure if its correct but seems to work in jshell

**Comment by giorgiocana** [comment]
So your method takes an operator instead?   `int compareTo(Operator<T> other) { ... }`

**Comment by tranquilityyy** [comment]
I initially thought to use instanceof Operator<?> to check if the object o is an operator (since I initially thought instanceof is allowed if "checking for an instance of its own class", but perhaps I wasn't using it correctly since codecrunch still blocks me from using this implementation.)

Not sure if anyone used something aside from instanceof or if the way I used instanceof was wrong such that it was still flagged by codecrunch despite the exception.

**Comment by wilsonwid** [comment]
@tranquilityyy I think the `instanceof` keyword is only allowed inside the `equals(Object o)` method.

**Comment by wilsonwid** [comment]
@giorgiocana Yes. The `compareTo()` method takes in an `Operator<T>`.

**Comment by giorgiocana** [comment]
@wilsonwid when I try that I get an error tho, because the method compareTo defined in the interface Comparable<T> takes in an object T, not an Operator<T>.

My Operator<T> is defined to implement Comparable<T>: `Operator<T> implements Comparable<T>`

<img width="824" alt="Screenshot 2022-11-09 at 13 41 03" src="https://user-images.githubusercontent.com/100380492/200748162-8dfd4014-7aea-490c-bea2-b407565ddc26.png">

**Comment by wilsonwid** [comment]
Then your `Operator` should implement the `Comparable<Operator<T>>` interface

**Comment by giorgiocana** [comment]
I see, I didn't think of that. Thank you sm!
