### ISSUE TITLE
Lab 8 failed test case 8_2

### ISSUE THREAD

**Issue by cherylchan02** [nus-cs2030/2223-s1#289]
## Description:

Customer 13 is waiting at server 1 even thought self-check 3 is free and I have no idea why. At line 48, customer 16 is served immediately by self-check 3 and self-check 3 did not finish serving anyone prior to that, so this means that self-check 3 is free but I don't know why customer 13 waits at 1 instead of going to self-check 3 which is free. I thought it was because my self-check was resting when it isn't supposed to but fixing that didn't resolve this issue. Currently at a loss of what else could have caused this. I would really appreciate any help thanks so much!

## Screenshots

<img width="607" alt="Screenshot 2022-11-13 at 11 58 23 AM" src="https://user-images.githubusercontent.com/113876601/201505041-ba300b1d-3409-4fa7-8c30-bbf3c1f814ba.png">

**Comment by Ryan-loves-movies** [comment]
Could you share how your self-check counters are implemented? 
Could be an issue with that. 

For context, for a situation with 2 self-check counters, my first implementation used a single queue with 2 servers and that caused an issue.

This is because 
when checking if the queues are empty, if one self-check counter is currently serving 1 other customer, the queue would no longer be empty.

**Comment by cherylchan02** [comment]
hi my self-check is a subclass of server that contains a list of servers which are the individual counters. In my implementation customers only join the queue if they wait, otherwise they go straight to being served without joining the queue.

**Comment by giorgiocana** [comment]
Hi, in my implementation, my Self-check counter has an int property that tells you how many free spots there are there in the counters queue at any given time. If you have a number of customers lower than the number of counters, the customers are served directly. If the queue is non-full, the customers join the queue and so on. 

Hope this helps!

**Comment by mohddanesh** [comment]
I have similar implementation as you. I don't know if your SelfCheck class has another attribute to store the number of queue. It seems that your customer will only be served by the counter if they get wait event when all servers are full. How about allocating customers in your arrive event? I think it would work better

**Comment by izascia256** [comment]
There is a high chance the error is in you self-check counters queueing system because I can see the following:

1. Line 15: Self-check counter 2 finished serving but customer is queueing even though the counter is free.

2. Line 48: It also seems that your self-check counter is not able to pull from their queue properly given that the self-counter 3 immediately served  customer 16 when there is already someone in queue at self-counter 2.

**Comment by wilsonwid** [comment]
I agree with @izascia256, but other potential errors include not correctly assigning the customers to the 'best' available self-checkout counter, as well as not continually updating the service end time for the self-checkout counters.

**Comment by shirohaku** [comment]
Could be your counter doesn't flag itself as free for some reason as well.

**Comment by wjiayis** [comment]
Hi Cheryl, perhaps you could check how you update the nextAvailableTime of your "self-check collection" object. I had a similar implementation as you, and my "self-check collection" takes minimum nextAvailableTime of all its counters. Hope it helps!

**Comment by cherylchan02** [comment]
asd

**Comment by cherylchan02** [comment]
Hi everyone thank you for all your suggestions, I managed to fix the issue. It was a variety of problems and all of your input really helped me with debugging.
