### ISSUE TITLE
Question on ? Extends Optional/Maybe

### ISSUE THREAD

**Issue by GarlicButterSteak** [nus-cs2030/2223-s1#299]
Hi all! I was attempting Exercise 5 and was wondering why we must have the following while implementing Level 5:

\? extends Maybe<? extends T>

I kinda don get why \Maybe<? extends T> is insufficient. My understanding was that Integer extends Object, and so that Maybe<Integer> extends Maybe<Object>, but this does not work. So what does it mean to extend a Maybe/Optional? Is there an intuitive way to think about this?

**Comment by junhuiii** [comment]
I don't think there's any misconception here, the reason why we have to put in a `? extends Maybe<...>` is simply because of the test-cases where in Level 4 and Level 5 a sub-class of maybe was created.

**Comment by JuliaPoo** [comment]
@GarlicButterSteak 
The reason why methods of `Monad<T>` would do `? extends Monad<? extends T>` is because such a method should

1. Be applicable to anything that extends `Monad`
2. Be applicable to anything that extends the object inside the `Monad`, i.e., should extend `T`.

This is the most general type description for arguments for methods like `.flatMap`. For instance, `.flatMap` operates on a `Monad` and so you should be able to put in anything that extends `Monad` and `.flatMap` should cast it back down to `Monad`. Next, the callback function you supply would input a `T` and so is applicable to anything that extends `T`. The callback function would just cast it back down to `T` when applying the callback.

**Comment by nixonwidjaja** [comment]
It's because the higher levels have test cases where subclass of Maybe is used instead of Maybe

**Comment by izascia256** [comment]
If you read Level 5 carefully, there is this part that says:
![image](https://user-images.githubusercontent.com/112748524/203711368-6b068bb8-afdd-420d-84ae-a42963d5bd2c.png)

The testcases will be using a subclass of `Maybe`. Therefore, `? extends Maybe` is needed.

**Comment by GarlicButterSteak** [comment]
Hi thank you so much for the responses everyone! 🙏
