### ISSUE TITLE
Lab 8: how to print self-check?

### ISSUE THREAD

**Issue by mohddanesh** [nus-cs2030/2223-s1#305]
I am stuck at how to print like "15 done serving by self-check 3". To specify my implementation, my SelfCheck is a list of servers. In order to add the selfcheck into the toString of each event, should I assign the server class an attribute indicating if it is a normal server or a self-check server?

**Comment by OngMinXian** [comment]
I personally used a boolean attribute to indicate whether a server is a self check out and then checking for it in my toString method.

**Comment by bransometan** [comment]
I am not sure if my approach may help you but I have implemented my SelfCheck as a subclass of Server. Then, I just overwrite the toString method. Hence, I do not need to worry about the printing.

**Comment by giorgiocana** [comment]
There are a few ways you can do this. I did it by having a method that returns the type of server (Human or Self), and my Serve and Done events will check for the kind of server and print the corresponding string.
Otherwise, you can make the server do the same job as suggested above. 
Another possible way could be working with the counters' indices. If index > number of human counters, you use the self-check name.

**Comment by sansuthn** [comment]
I also have a boolean for Server called isHuman, and when i need the Server's name, ill check the boolean to issue the right name

**Comment by mohddanesh** [comment]
thanks for all the input!
