### ISSUE TITLE
Difference between Stream<Integer> and IntStream

### ISSUE THREAD

**Issue by KEEWEIKUANG** [nus-cs2030/2223-s1#329]
Hello! May i know what is the difference between Stream<Integer> and IntStream? 

Also, whats the difference between a Stream.Iterate() and Intstream.Iterate(). Thanks!!

**Comment by wishdbekuc** [comment]
streams accept all kinds of classes. eg u can have stream<Circle> or stream<String>

intstream is a particular kind of steam that only take in integers eg stream<Integer>

iterate returns an infinite stream of whatever type you specified as the stream type

in the case of intstream it returns an infinite stream of integers

theres an overloaded form of iterate that takes in a predicate too that allows you to cap the stream on a particular condition (aka make the stream not infinite)

**Comment by izascia256** [comment]
`IntStream` takes in primitive `int` values while `Stream<Integer>` takes in the `Integer` object. So it means that:
`Stream.<Integer>of(1, 2, 3).forEach(x -> System.out.println(x.toString()))` works
but `IntStream.of(1, 2, 3).forEach(x -> System.out.println(x.toString()))` doesn't, since the primitive `int` type doesn't have a `toString()` method.

`IntStream` will have more built in functions for dealing with integers specifically such as `IntStream::sum`.

As for the `iterate` methods.
There is no difference as for as I know.
i.e.
![image](https://user-images.githubusercontent.com/112748524/204291616-35899d61-c9b4-4942-a731-e22fc6905aa2.png)

**Comment by KEEWEIKUANG** [comment]
Thanks both!

**Comment by ShiJiaAo** [comment]
something else that's cool is that you can map elements in a Stream<Integer> into a different Stream<R>. can check out prof's solution to AY21/22 Sem 1 Q3d. Can't do that with IntStreams; they can only stay as Integers!

**Comment by KEEWEIKUANG** [comment]
Thank you!
