### ISSUE TITLE
possible typo in task content of Lab 3

### ISSUE THREAD

**Issue by Jiaweilin001** [nus-cs2030/2223-s1#52]
# Summary
Hello, in the attached screenshot, pq.add(1).add(2).add(3) results in pq = [3, 1, 2]. is it a "typo"? Or perhaps does it have something to do with the second line where it says "output of elements in a priority queue is not necessarily in order"? I would like to understand why it is not necessarily in order and can the output of elements in a priority queue be relied on to give an accurate picture of what is inside the priority queue?

## Screenshots

![image](https://user-images.githubusercontent.com/85467935/189488846-dc0775cc-d0b5-444c-89a7-7b3adec0fa55.png)

**Comment by XihuaZ** [comment]
when u add, u need to write `pq = pq.add()`. `pq.add()` would not update the list, as `pq.add()` actually returns a new PQ

**Comment by junhuiii** [comment]
The inner workings of a PQ will be what you learn in Week 6/7 of CS2040, also called Binary Max/Min Heap, which is essentially a binary tree. The data is stored in an array/arraylist, but it is not in order. Only the root of the tree has the largest/smallest element depending on priority, and the rest will not be exactly ascending/descending order. 

That is why in Lab #3's example, you see that when 1, 2, 3 is added in that order, you see 3 in its correct position, because it is the largest, but 1 and 2 will not be in order. You can also try it out with other numbers.

**Comment by Jiaweilin001** [comment]
the following answer came from my TA (in case anyone is interested to learn the inner working of a priority queue) and also the comment by junhuiii was really insightful

The data stored in the Priority Queue will not be in order because of how the priority queue is structured internally. Only the head of the PQ will be guaranteed in order, as a PQ is actually a Binary Max/Min heap that has a tree-like structure (Note: even though the PQ has a tree-like structure, it can actually be implemented with an array). Every time you poll something out, the PQ will rearrange to make sure that the node with the next greatest priority is at the root of the tree (i.e. top of the tree). 
How java actually implements the PQ is unknown, but theoretically, we know that the PQ needs to maintain the heap structure by following its property. 
For Max Heap, it will be: the value of each node is less than or equal to the value of its parent, with the maximum-value element at the root. Therefore, each time an add() method is called, a new node will be created. This node will insert itself into the heap structure and move by comparing to its parent.

For more information:
https://visualgo.net/en/heap
https://en.m.wikipedia.org/wiki/Binary_heap (You can see the array representation here)
