### ISSUE TITLE
Exercise 4 level 5 accessing Grid2D get() method

### ISSUE THREAD

**Issue by zhanyi3** [nus-cs2030/2223-s1#67]
hi, I am trying to implement the `move()` method, but I got the "cannot find symbol" Error. can anyone explain to me why is this the case? for information, I implemented my constructor for puzzle with `this.puzzle = new Grid<Integer>(list, n)` 
<img width="225" alt="Screenshot 2022-09-13 at 6 25 41 PM" src="https://user-images.githubusercontent.com/105008161/189878645-e77370fc-6ba3-42d0-985f-d1df749b2230.png">

**Comment by junhuiii** [comment]
If you did the previous levels correctly, your implementation should be such that Puzzle has-a Grid2D. The Grid2D Class is the one with the .get() method, not Puzzle, which is why when you try to call .get() on puzzle, it can't find the method.

If you want to use p.get(), you would need to define a method in Puzzle itself that calls Grid2D's .get() method, although I think that is not necessary since you only need to create move() and isSolved().

**Comment by zhanyi3** [comment]
> If you did the previous levels correctly, your implementation should be such that Puzzle has-a Grid2D. The Grid2D Class is the one with the .get() method, not Puzzle, which is why when you try to call .get() on puzzle, it can't find the method.
> 
> If you want to use p.get(), you would need to define a method in Puzzle itself that calls Grid2D's .get() method, although I think that is not necessary since you only need to create move() and isSolved().

sorry I still don't really understand. Is this `this.puzzle = new Grid<Integer>(list, n)` not correct? what am I missing?

**Comment by bryanolm99** [comment]
`this.puzzle = new Grid<Integer>(list, n)` is fine.

But in your jshell, p refers to an instance of `Puzzle` and not the property `puzzle` that each `Puzzle` instance is expected to have. So what you're doing here is `Puzzle.get()`, whereas what you probably wanted to do is `Puzzle.puzzle.get()`.

**Comment by bransometan** [comment]
Use Puzzle.puzzle.get() since the get() method is defined in Grid2D class and you have assigned it to this.puzzle. I would suggest to rename this.puzzle to this.grid2D, etc to differentiate since it may cause some minor confusion. It is also more intuitive to name it to this.grid2D since the Puzzle has-a Grid2D instead of Puzzle has-a puzzle.

**Comment by zhanyi3** [comment]
alright thx! I see where's the problem
