### ISSUE TITLE
Pair variable not yet initalised in class

### ISSUE THREAD

**Issue by shuenCHANG25** [nus-cs2030/2223-s1#68]
Trying to declare a Pair in class, encountering "not yet initalised issue"

So I'm trying to create declare a Pair<T,U> in my events class. 

example:

```
private final Pair<String, Double> examplePair;

Constructor(String s, Double d) {
this.examplePair<String, Double> = new Pair(s, d);
}

```

compiler returns a "examplePair might not have been initalised" error.

since i need the values to be taken in when creating a new event object, and also that all variables need to be final, i am unable to initalise a pair first and change it later. is there any way to work around this issue? my brain has been fried for a few days now and i'm unable to come up with a smart solution, thanks! :)

**Comment by GarlicButterSteak** [comment]
Hello! I'm not sure what your main solution is, but since the usage of pairs is kinda dynamic for our lab, we may want to use and generate pairs within the main class instead of declaring it as a property of the event class...? Or alternatively if your solution necessarily requires what you said, then what we can do (or at least from my sloppy perspective) is to overload another pair constructor within the events class to first solve the initialising error, i.e., something like the following, I think...?

`Constructor() {
    this(FAKE_STRING, FAKE_DOUBLE);
}
`

As for changing the pair specifically, it might be difficult if it is a property of an event (since we require the finality), so maybe what has to be done would be to create a method to return an entirely new event instance that constructs a new pair at the same time. Hopefully, some of this made sense and is of some help!

**Comment by shirohaku** [comment]
Is there another constructor that you have not initialised examplePair for? Also, I think you shouldn't need to include <String, Double> in the Constructor, just `this.examplePair = new Pair(s, d);` should do.

**Comment by mohddanesh** [comment]
maybe you can consider use the pair class given on the main class instead of making your own one and put it in event. this method sounds really complex

**Comment by shuenCHANG25** [comment]
late reply but thanks all for the help!! i managed to solve it :D
