### ISSUE TITLE
Lab 4 Level 3 test3.jsh 

### ISSUE THREAD

**Issue by OngMinXian** [nus-cs2030/2223-s1#82]
Has anyone got the issue where the amount calculated is wrong sometimes? 

![image](https://user-images.githubusercontent.com/95210624/190707817-ffe7dedd-f827-4a6a-8a09-d64663b1c50d.png)

![image](https://user-images.githubusercontent.com/95210624/190707837-10286edb-7e0b-40f1-bead-e22180d1ff68.png)

I tried printing the test cases and found out that the request is 27km for 3 pax at 600hrs. 
How would the cheapest cost be $0.22 using the way it is calculated in the question?

My current implementation does the calculation of the service given a request inside a service and then determines which is the cheaper service inside the driver. Is there something wrong with my approach?

Thanks!

**Comment by quek-zhiheng** [comment]
Personally, I delegated the implementation of `computeFare()` to the Request instance, which could also be easier to implement given the Level 2 requirements! I chose to implement the logic of getting the cheaper service inside the Booking class as a private method instead since its quite convenient that Booking is constructed with a Service and Booking instance!

**Comment by danqiye1** [comment]
Hi, somehow your output is in reverse order as the expected output. One quick check is to make sure your compareTo method is not reversed.

**Comment by OngMinXian** [comment]
> Hi, somehow your output is in reverse order as the expected output. One quick check is to make sure your compareTo method is not reversed.

Thanks! Turns out that was indeeed the problem!
