### ISSUE TITLE
Self-Practice Recommendations

### ISSUE THREAD

**Issue by GarlicButterSteak** [nus-cs2030/2223-s1#9]
Hello all! I am looking to improve my programming skills/computational thinking **specifically relevant to this module's topics**. Given that my only computing experience is CS1010 from a year ago, and suppose that I am willing to dedicate 1-2 hours of extra time per week to self-practice in addition to the module exercises/labs, how best should I go about this?

I was thinking of following a practice problems book (as compact as possible 🤣), though I do not know where to find such a book, but I am open to any other recommended resources as well. Looking forward to any suggestions for resources and/or tips! Thank you!

**Comment by danqiye1** [comment]
Hi, it is great that you want to put in extra practice! For CS2030, I would think that the exercises and labs are enough, as long as you complete them. You should also code the programs snippets from lecture and recitations to see the behavior for yourself. Hit those compile errors yourself so you learn to debug your own programs. Also learn to read to Java API docs to figure out how you should use classes from Java.

There is no practice book suitable for this class, but if you still need more practice, try to come up with interesting problems with friends.

**Comment by eLTehh** [comment]
Student here; disclaimer that I am not a TA and speaking from experience 

One thing that helped me ease into CS2030 is coding a decently big OOP project over the summer break. I made a lot of mistakes, and I struggled to prevent code from growing too unwieldy. When CS2030 started and the lecturer went over the OOP principles, a lot of things clicked for me since I had made mistakes (circular dependency especially) where it would have helped to organize my code a bit better.

I'd say find something you're passionate about and do a medium scale coding project. You'll make a lot of mistakes along the way (and it may be possible you won't even finish) but experience helps, a lot.

For some ideas, maybe a Discord/telegram bot with functions that build on top of each other? Or a small text-based game, since games have many different moving parts that build on one another. The former would require some research on external libraries (which is out of scope for CS2030) but is easier to see how things apply to something you use frequently.

**Comment by GarlicButterSteak** [comment]
Thank you very much for the suggestions and tips everyone! 🙏

**Comment by danqiye1** [comment]
This is not an official textbook for CS2030, but I would recommend the book "Effective Java". A lot of the concepts taught in CS2030 seems to be explained inside.

**Comment by GarlicButterSteak** [comment]
Looks really good, thank you!
