### ISSUE TITLE
not declared private final for protected final variables 

### ISSUE THREAD

**Issue by joeyHXD** [nus-cs2030/2223-s1#90]
## Summary
Clarification about the usage of protected variables.
## Details
I wanted to make Driver an abstract class so that I can inherit some methods for NormalCab and PrivateCar in lab 4.

`abstract class Driver {
    protected final String lisence;
    protected final int waitTime;
}
`

but I ran into this error.

![image](https://user-images.githubusercontent.com/68325229/190915673-22f57992-87bd-44b8-b38f-b0b4eebf4484.png)

I believe this means that we cannot use protected final and have to use private final instead? 
Or is this some error in the stylechecker? since the lecture slide wrote about protected final variable. 

![image](https://user-images.githubusercontent.com/68325229/190916036-4284e6fd-6b82-4a36-a303-e91d7a1680ea.png)

**Comment by xuan-jun** [comment]
Hello, if I am not wrong, the only place we can use `protected final` is under the Project for `Events`. 

For this case, you could consider if you really need `NormalCab` and `PrivateCab` to have access to the properties under `Driver`. 
If you only require certain methods from `Driver`, you can consider just calling the methods rather than getting the attributes explicitly else I think you could use getters instead. Hope this helps!

**Comment by joeyHXD** [comment]
> Hello, if I am not wrong, the only place we can use `protected final` is under the Project for `Events`.
> 
> For this case, you could consider if you really need `NormalCab` and `PrivateCab` to have access to the properties under `Driver`. If you only require certain methods from `Driver`, you can consider just calling the methods rather than getting the attributes explicitly else I think you could use getters instead. Hope this helps!

Oh i see. 
I'm just curious whether protected is allowed or not. ;)
